### ISSUE TITLE
Migrate syft.js to use Protobuf classes

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/syft.js#83]
We need to add the following Protobuf classes to syft.js as they are completed:

Deserialize from protobuf:
- [x] `Plan` 
- [x] `State`
- [x] `Operation`
- [x] `ObjectMessage`
- [x] `Placeholder`
- [x] `TorchTensor`
- [x] `TorchParameter`
- [x] `Protocol` (old one)
- [ ] `PromiseTensor` (not implemented in PySyft yet)
- [x] `PointerTensor`
- [ ] ... more to be defined

Serialize to protobuf:
- [ ] `Plan` 
- [x] `State`
- [ ] `Operation`
- [ ] `ObjectMessage`
- [x] `Placeholder`
- [x] `TorchTensor`
- [ ] `TorchParameter`
- [ ] `Protocol` (old one)
- [ ] `PromiseTensor` (not implemented in PySyft yet)
- [ ] `PointerTensor`
- [ ] ... more to be defined
